import { useMemo, useState } from 'react'
import { api } from '../api'
import DirectorySkeleton from './DirectorySkeleton'

const COLLECTIONS={
 students:{title:'O‘quvchilar',add:'O‘quvchi qo‘shish',icon:'♧',fields:['name','surname','age','gender','class','phone','email','address','parentId','teacherId','averageScore','attendance']},
 parents:{title:'Ota-onalar',add:'Ota-ona qo‘shish',icon:'♙',fields:['name','surname','phone','email','job','address','studentId']},
 teachers:{title:'O‘qituvchilar',add:'O‘qituvchi qo‘shish',icon:'✦',fields:['name','surname','subject','phone','email','experience','class']},
 users:{title:'Foydalanuvchilar',add:'Foydalanuvchi qo‘shish',icon:'♙',fields:['name','surname','phone','password','email','role','status']},
 courses:{title:'Kurslar',add:'Kurs qo‘shish',icon:'▤',fields:['name','description','category','duration','level','price','studentsCount','teacher','language','status']},
 groups:{title:'Guruhlar',add:'Guruh qo‘shish',icon:'▦',fields:['name','courseId','courseName','learningCenter','teacher','studentsCount','maxStudents','room','days','startTime','endTime','startDate','status']}
}
const labels={name:'Ism',surname:'Familiya',age:'Yosh',gender:'Jinsi',class:'Sinf',phone:'Telefon',email:'Email',address:'Manzil',parentId:'Ota-ona ID',teacherId:'O‘qituvchi ID',averageScore:'O‘rtacha baho',attendance:'Davomat (%)',job:'Kasbi',studentId:'O‘quvchi ID',subject:'Fan',experience:'Tajriba (yil)',password:'Parol',role:'Rol',status:'Holat',description:'Tavsif',category:'Yo‘nalish',duration:'Davomiyligi',level:'Daraja',price:'Narxi',studentsCount:'O‘quvchilar soni',teacher:'O‘qituvchi',language:'Til',courseId:'Kurs ID',courseName:'Kurs nomi',learningCenter:'Ta’lim markazi',maxStudents:'Maksimal o‘rin',room:'Xona',days:'Hafta kunlari',startTime:'Boshlanish vaqti',endTime:'Tugash vaqti',startDate:'Boshlanish sanasi'}
const display=value=>Array.isArray(value)?value.join(', '):value===null||value===undefined||value===''?'—':typeof value==='object'?JSON.stringify(value):String(value)
export default function ArrayDirectory({collection,rows=[],refresh,loading=false,error:loadError=''}){
 const config=COLLECTIONS[collection], [query,setQuery]=useState(''),[dialog,setDialog]=useState(null),[form,setForm]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const fields=useMemo(()=>[...new Set([...Object.keys(rows[0]||{}).filter(key=>key!=='id'),...config.fields])],[rows,config])
 const visibleFields=fields.filter(key=>key!=='password')
 const filtered=useMemo(()=>rows.filter(row=>Object.values(row).some(value=>display(value).toLowerCase().includes(query.toLowerCase()))),[rows,query])
 const open=(mode,row)=>{setError('');setDialog({mode,row});setForm(row?{...row}:Object.fromEntries(fields.map(key=>[key,''])))}
 const save=async event=>{event.preventDefault();setBusy(true);setError('');try{const payload={};for(const key of fields){let value=form[key];if(key==='password'&&!value&&dialog.mode==='edit')continue;if(Array.isArray(rows[0]?.[key]))value=String(value||'').split(',').map(part=>part.trim()).filter(Boolean);else if(typeof rows[0]?.[key]==='number'&&value!=='')value=Number(value);payload[key]=value}const result=dialog.mode==='add'?await api.createCollectionItem(collection,payload):await api.updateCollectionItem(collection,dialog.row.id,payload);if(result?.error)throw new Error(result.error);await refresh();setDialog(null)}catch(err){setError(err.message||'Saqlashda xatolik yuz berdi')}finally{setBusy(false)}}
 const remove=async()=>{setBusy(true);setError('');try{const result=await api.deleteCollectionItem(collection,dialog.row.id);if(result?.error)throw new Error(result.error);await refresh();setDialog(null)}catch(err){setError(err.message||'O‘chirishda xatolik yuz berdi')}finally{setBusy(false)}}
 return <><div className="page-intro mb-6 flex items-center justify-between gap-4"><div><div className="eyebrow">MAKTAB MA’LUMOTLARI</div><h2>{config.title}</h2><p>data.json ichidagi {collection} API kolleksiyasi</p></div><button className="primary-action" onClick={()=>open('add')}><span>＋</span>{config.add}</button></div>
 <section className="directory-card overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-900"><div className="directory-head flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 p-5 dark:border-slate-700"><div><h3>{config.title} <span className="count-chip">{filtered.length}</span></h3><p>Ma’lumotlar API’dan olinadi va o‘zgarishlar API’ga yoziladi</p></div><div className="searchbox"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Qidirish…"/></div></div>{loadError&&<div className="form-error" role="alert">{loadError}</div>}<div className="table-wrap overflow-x-auto" aria-busy={loading}>{loading&&<DirectorySkeleton columns={visibleFields.length}/>}<table className="directory-table array-table" style={loading?{display:'none'}:undefined}><thead><tr>{visibleFields.map(key=><th key={key}>{labels[key]||key}</th>)}<th>AMALLAR</th></tr></thead><tbody>{filtered.map((row,index)=><tr key={row.id??index}>{visibleFields.map(key=><td key={key}>{key==='status'?<span className={`class-pill ${row[key]==='active'?'status-active':''}`}>{display(row[key])}</span>:display(row[key])}</td>)}<td><div className="row-actions"><button className="edit-action" onClick={()=>open('edit',row)}>Tahrirlash</button><button className="delete-action" onClick={()=>{setError('');setDialog({mode:'delete',row})}} aria-label="O‘chirish">⌫</button></div></td></tr>)}</tbody></table>{!loading&&!filtered.length&&<div className="empty-directory"><div>{config.icon}</div><b>{query?'Qidiruv bo‘yicha ma’lumot topilmadi':`${config.title} ro‘yxati bo‘sh`}</b><span>{!query&&'Yangi ma’lumot qo‘shish tugmasini bosing.'}</span></div>}</div></section>
 {dialog&&<div className="modal-backdrop" onMouseDown={event=>event.target===event.currentTarget&&setDialog(null)}><section className="school-modal array-modal"><button className="modal-close" onClick={()=>setDialog(null)}>×</button>{dialog.mode==='delete'?<><div className="modal-symbol danger-symbol">⌫</div><h3>O‘chirishni tasdiqlaysizmi?</h3><p>Tanlangan yozuv API’dan o‘chiriladi.</p>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-action" onClick={()=>setDialog(null)}>Bekor qilish</button><button className="danger-action" onClick={remove} disabled={busy}>{busy?'O‘chirilmoqda…':'Ha, o‘chirish'}</button></div></>:<><div className="modal-symbol">{dialog.mode==='add'?'＋':'✎'}</div><h3>{dialog.mode==='add'?config.add:`${config.title} мэдээллийг tahrirlash`}</h3><p>Maydonlarni to‘ldiring va saqlang.</p><form onSubmit={save}><div className="form-grid">{fields.map(key=><label key={key}>{labels[key]||key}{key==='gender'||key==='role'||key==='status'?<select value={form[key]??''} required onChange={event=>setForm({...form,[key]:event.target.value})}>{!form[key]&&<option value="">Tanlang</option>}{(key==='gender'?['male','female']:key==='role'?['admin','student','teacher','parent']:['active','inactive']).map(option=><option key={option} value={option}>{option}</option>)}</select>:<input type={key==='password'?'password':key==='email'?'email':'text'} required={key==='password'?dialog.mode==='add':key==='name'||key==='phone'} value={Array.isArray(form[key])?form[key].join(', '):form[key]??''} placeholder={key==='password'&&dialog.mode==='edit'?'O‘zgartirmasangiz bo‘sh qoldiring':key==='days'?'Vergul bilan ajrating':''} onChange={event=>setForm({...form,[key]:event.target.value})}/>}</label>)}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={()=>setDialog(null)}>Bekor qilish</button><button className="primary-action" disabled={busy}>{busy?'Saqlanmoqda…':'Saqlash'}</button></div></form></>}</section></div>}
 </>
}
