import { useMemo, useState } from 'react'
import { api } from '../api'

const blank={name:'',phone:'',email:'',password:'',className:'',subject:''}
export default function UserDirectory({users,refresh,role,title,subtitle,buttonLabel,emptyLabel}) {
 const [query,setQuery]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState(blank),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const rows=useMemo(()=>users.filter(u=>u.role===role&&`${u.name} ${u.phone} ${u.email||''} ${u.className||''}`.toLowerCase().includes(query.toLowerCase())),[users,role,query])
 const open=(u=null)=>{setError('');setForm(u?{...blank,...u,password:''}:{...blank});setModal(u?{type:'edit',user:u}:{type:'add'})}
 const save=async(e)=>{e.preventDefault();setSaving(true);setError('');try{const payload={...form,role};if(!payload.password)delete payload.password;const res=modal.type==='add'?await api.createUser(payload):await api.updateUser(modal.user.id,payload);if(res?.error)throw new Error(res.error);await refresh();setModal(null)}catch(err){setError(err.message||'Saqlashda xatolik yuz berdi')}finally{setSaving(false)}}
 const remove=async()=>{setSaving(true);try{const res=await api.deleteUser(modal.user.id);if(res?.error)throw new Error(res.error);await refresh();setModal(null)}catch(err){setError(err.message)}finally{setSaving(false)}}
 return <><div className="page-intro"><div><div className="eyebrow">MAKTAB JAMOASI</div><h2>{title}</h2><p>{subtitle}</p></div><button className="primary-action" onClick={()=>open()}><span>＋</span>{buttonLabel}</button></div>
 <section className="directory-card"><div className="directory-head"><div><h3>{title} ro‘yxati <span className="count-chip">{rows.length}</span></h3><p>Barcha ma’lumotlar API bilan sinxronlanadi</p></div><div className="searchbox"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ism yoki telefon bo‘yicha qidirish"/></div></div>
 <div className="table-wrap"><table className="directory-table"><thead><tr><th>ISM FAMILIYA</th><th>TELEFON</th><th>EMAIL</th><th>{role==='oquvchi'?'SINF':'MA’LUMOT'}</th><th>AMALLAR</th></tr></thead><tbody>{rows.map((u,i)=><tr key={u.id}><td><div className="person-cell"><div className={`person-avatar avatar-${i%5}`}>{u.avatar||u.name?.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><b>{u.name}</b><small>ID: {u.id}</small></div></div></td><td>{u.phone||'—'}</td><td>{u.email||'—'}</td><td>{role==='oquvchi'?<span className="class-pill">{u.className||'Sinf belgilanmagan'}</span>:<span className="muted-data">{u.subject||'—'}</span>}</td><td><div className="row-actions"><button className="edit-action" onClick={()=>open(u)}>Tahrirlash</button><button className="delete-action" onClick={()=>{setError('');setModal({type:'delete',user:u})}} aria-label="O‘chirish">⌫</button></div></td></tr>)}</tbody></table>{rows.length===0&&<div className="empty-directory"><div>♧</div><b>{emptyLabel}</b><span>Yangi yozuv qo‘shish tugmasini bosing.</span></div>}</div></section>
 {modal&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setModal(null)}><section className="school-modal"><button className="modal-close" onClick={()=>setModal(null)}>×</button>{modal.type==='delete'?<><div className="modal-symbol danger-symbol">⌫</div><h3>O‘chirishni tasdiqlaysizmi?</h3><p><b>{modal.user.name}</b> ro‘yxatdan o‘chiriladi. Bu amalni bekor qilib bo‘lmaydi.</p>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button className="secondary-action" onClick={()=>setModal(null)}>Bekor qilish</button><button className="danger-action" onClick={remove} disabled={saving}>{saving?'O‘chirilmoqda…':'Ha, o‘chirish'}</button></div></>:<><div className="modal-symbol">{modal.type==='edit'?'✎':'＋'}</div><h3>{modal.type==='edit'?'Ma’lumotlarni tahrirlash':buttonLabel}</h3><p>Kerakli maydonlarni kiriting va saqlang.</p><form onSubmit={save}><div className="form-grid"><label>Ism familiya<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Masalan, Aliyev Sardor"/></label><label>Telefon raqam<input required value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="+998 90 123 45 67"/></label><label>Email<input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@example.com"/></label><label>{modal.type==='edit'?'Yangi parol (ixtiyoriy)':'Parol'}<input required={modal.type==='add'} type="password" value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})} placeholder={modal.type==='edit'?'O‘zgartirmaslik uchun bo‘sh qoldiring':'Kamida 6 belgi'}/></label>{role==='oquvchi'&&<label>Sinf<input value={form.className||''} onChange={e=>setForm({...form,className:e.target.value})} placeholder="Masalan, 7-A"/></label>}{role==='oqituvchi'&&<label>Fan<input value={form.subject||''} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Masalan, Matematika"/></label>}</div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary-action" onClick={()=>setModal(null)}>Bekor qilish</button><button className="primary-action" disabled={saving}>{saving?'Saqlanmoqda…':'Saqlash'}</button></div></form></>}</section></div>}
 </>
}
